package com.crm.pojo;
// Generated 2017-7-24 17:26:14 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CrmClass generated by hbm2java
 */
public class CrmClass implements java.io.Serializable {

	private Long classId;
	private CrmCourseType crmCourseType;
	private String className;
	private Long beginTime;
	private Long endTime;
	private String status;
	private Integer totalCount;
	private Integer upgradeCount;
	private Integer changeCount;
	private Integer runoffCount;
	private String remark;
	private String uploadPath;
	private String uploadFileName;
	private Long uploadTime;
	private Set crmStudents = new HashSet(0);
	private Set crmGraduates = new HashSet(0);
	private Set crmRefers = new HashSet(0);

	public CrmClass() {
	}

	public CrmClass(CrmCourseType crmCourseType, String className, Long beginTime, Long endTime, String status,
			Integer totalCount, Integer upgradeCount, Integer changeCount, Integer runoffCount, String remark,
			String uploadPath, String uploadFileName, Long uploadTime, Set crmStudents, Set crmGraduates,
			Set crmRefers) {
		this.crmCourseType = crmCourseType;
		this.className = className;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.status = status;
		this.totalCount = totalCount;
		this.upgradeCount = upgradeCount;
		this.changeCount = changeCount;
		this.runoffCount = runoffCount;
		this.remark = remark;
		this.uploadPath = uploadPath;
		this.uploadFileName = uploadFileName;
		this.uploadTime = uploadTime;
		this.crmStudents = crmStudents;
		this.crmGraduates = crmGraduates;
		this.crmRefers = crmRefers;
	}

	public Long getClassId() {
		return this.classId;
	}

	public void setClassId(Long classId) {
		this.classId = classId;
	}

	public CrmCourseType getCrmCourseType() {
		return this.crmCourseType;
	}

	public void setCrmCourseType(CrmCourseType crmCourseType) {
		this.crmCourseType = crmCourseType;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Long getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Long beginTime) {
		this.beginTime = beginTime;
	}

	public Long getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Long endTime) {
		this.endTime = endTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getTotalCount() {
		return this.totalCount;
	}

	public void setTotalCount(Integer totalCount) {
		this.totalCount = totalCount;
	}

	public Integer getUpgradeCount() {
		return this.upgradeCount;
	}

	public void setUpgradeCount(Integer upgradeCount) {
		this.upgradeCount = upgradeCount;
	}

	public Integer getChangeCount() {
		return this.changeCount;
	}

	public void setChangeCount(Integer changeCount) {
		this.changeCount = changeCount;
	}

	public Integer getRunoffCount() {
		return this.runoffCount;
	}

	public void setRunoffCount(Integer runoffCount) {
		this.runoffCount = runoffCount;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUploadPath() {
		return this.uploadPath;
	}

	public void setUploadPath(String uploadPath) {
		this.uploadPath = uploadPath;
	}

	public String getUploadFileName() {
		return this.uploadFileName;
	}

	public void setUploadFileName(String uploadFileName) {
		this.uploadFileName = uploadFileName;
	}

	public Long getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Long uploadTime) {
		this.uploadTime = uploadTime;
	}

	public Set getCrmStudents() {
		return this.crmStudents;
	}

	public void setCrmStudents(Set crmStudents) {
		this.crmStudents = crmStudents;
	}

	public Set getCrmGraduates() {
		return this.crmGraduates;
	}

	public void setCrmGraduates(Set crmGraduates) {
		this.crmGraduates = crmGraduates;
	}

	public Set getCrmRefers() {
		return this.crmRefers;
	}

	public void setCrmRefers(Set crmRefers) {
		this.crmRefers = crmRefers;
	}

}
