package com.crm.pojo;
// Generated 2017-7-24 17:26:14 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CrmCourseType generated by hbm2java
 */
public class CrmCourseType implements java.io.Serializable {

	private long courseTypeId;
	private Double courseCost;
	private Integer total;
	private String courseName;
	private String remark;
	private Set crmClasses = new HashSet(0);

	public CrmCourseType() {
	}

	public CrmCourseType(long courseTypeId) {
		this.courseTypeId = courseTypeId;
	}

	public CrmCourseType(long courseTypeId, Double courseCost, Integer total, String courseName, String remark,
			Set crmClasses) {
		this.courseTypeId = courseTypeId;
		this.courseCost = courseCost;
		this.total = total;
		this.courseName = courseName;
		this.remark = remark;
		this.crmClasses = crmClasses;
	}

	public long getCourseTypeId() {
		return this.courseTypeId;
	}

	public void setCourseTypeId(long courseTypeId) {
		this.courseTypeId = courseTypeId;
	}

	public Double getCourseCost() {
		return this.courseCost;
	}

	public void setCourseCost(Double courseCost) {
		this.courseCost = courseCost;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getCrmClasses() {
		return this.crmClasses;
	}

	public void setCrmClasses(Set crmClasses) {
		this.crmClasses = crmClasses;
	}

}
