package com.crm.pojo;
// Generated 2017-7-24 17:26:14 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CrmDepartment generated by hbm2java
 */
public class CrmDepartment implements java.io.Serializable {

	private long depId;
	private String depName;
	private Set crmPosts = new HashSet(0);

	public CrmDepartment() {
	}

	public CrmDepartment(long depId) {
		this.depId = depId;
	}

	public CrmDepartment(long depId, String depName, Set crmPosts) {
		this.depId = depId;
		this.depName = depName;
		this.crmPosts = crmPosts;
	}

	public long getDepId() {
		return this.depId;
	}

	public void setDepId(long depId) {
		this.depId = depId;
	}

	public String getDepName() {
		return this.depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	public Set getCrmPosts() {
		return this.crmPosts;
	}

	public void setCrmPosts(Set crmPosts) {
		this.crmPosts = crmPosts;
	}

}
