package com.crm.pojo;
// Generated 2017-7-24 17:26:14 by Hibernate Tools 5.2.3.Final

/**
 * CrmFollow generated by hbm2java
 */
public class CrmFollow implements java.io.Serializable {

	private Long followId;
	private CrmRefer crmRefer;
	private CrmStaff crmStaff;
	private Long followTime;
	private String content;

	public CrmFollow() {
	}

	public CrmFollow(CrmRefer crmRefer, CrmStaff crmStaff, Long followTime, String content) {
		this.crmRefer = crmRefer;
		this.crmStaff = crmStaff;
		this.followTime = followTime;
		this.content = content;
	}

	public Long getFollowId() {
		return this.followId;
	}

	public void setFollowId(Long followId) {
		this.followId = followId;
	}

	public CrmRefer getCrmRefer() {
		return this.crmRefer;
	}

	public void setCrmRefer(CrmRefer crmRefer) {
		this.crmRefer = crmRefer;
	}

	public CrmStaff getCrmStaff() {
		return this.crmStaff;
	}

	public void setCrmStaff(CrmStaff crmStaff) {
		this.crmStaff = crmStaff;
	}

	public Long getFollowTime() {
		return this.followTime;
	}

	public void setFollowTime(Long followTime) {
		this.followTime = followTime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
