package com.crm.pojo;
// Generated 2017-7-24 17:26:14 by Hibernate Tools 5.2.3.Final

/**
 * CrmGraduate generated by hbm2java
 */
public class CrmGraduate implements java.io.Serializable {

	private Long granduateId;
	private CrmClass crmClass;
	private CrmStudent crmStudent;
	private String companyName;
	private String salary;
	private String post;
	private Long entryTime;
	private String remark;

	public CrmGraduate() {
	}

	public CrmGraduate(CrmClass crmClass, CrmStudent crmStudent, String companyName, String salary, String post,
			Long entryTime, String remark) {
		this.crmClass = crmClass;
		this.crmStudent = crmStudent;
		this.companyName = companyName;
		this.salary = salary;
		this.post = post;
		this.entryTime = entryTime;
		this.remark = remark;
	}

	public Long getGranduateId() {
		return this.granduateId;
	}

	public void setGranduateId(Long granduateId) {
		this.granduateId = granduateId;
	}

	public CrmClass getCrmClass() {
		return this.crmClass;
	}

	public void setCrmClass(CrmClass crmClass) {
		this.crmClass = crmClass;
	}

	public CrmStudent getCrmStudent() {
		return this.crmStudent;
	}

	public void setCrmStudent(CrmStudent crmStudent) {
		this.crmStudent = crmStudent;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public Long getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Long entryTime) {
		this.entryTime = entryTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
