package com.crm.pojo;
// Generated 2017-7-24 17:26:14 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CrmRefer generated by hbm2java
 */
public class CrmRefer implements java.io.Serializable {

	private Long referId;
	private CrmClass crmClass;
	private CrmStaff crmStaff;
	private String stuName;
	private String telephone;
	private String qq;
	private Long createDate;
	private String intentionLevel;
	private Long courseTypeId;
	private String source;
	private String status;
	private String remark;
	private Set crmFollows = new HashSet(0);

	public CrmRefer() {
	}

	public CrmRefer(CrmClass crmClass, CrmStaff crmStaff, String stuName, String telephone, String qq, Long createDate,
			String intentionLevel, Long courseTypeId, String source, String status, String remark, Set crmFollows) {
		this.crmClass = crmClass;
		this.crmStaff = crmStaff;
		this.stuName = stuName;
		this.telephone = telephone;
		this.qq = qq;
		this.createDate = createDate;
		this.intentionLevel = intentionLevel;
		this.courseTypeId = courseTypeId;
		this.source = source;
		this.status = status;
		this.remark = remark;
		this.crmFollows = crmFollows;
	}

	public Long getReferId() {
		return this.referId;
	}

	public void setReferId(Long referId) {
		this.referId = referId;
	}

	public CrmClass getCrmClass() {
		return this.crmClass;
	}

	public void setCrmClass(CrmClass crmClass) {
		this.crmClass = crmClass;
	}

	public CrmStaff getCrmStaff() {
		return this.crmStaff;
	}

	public void setCrmStaff(CrmStaff crmStaff) {
		this.crmStaff = crmStaff;
	}

	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public Long getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Long createDate) {
		this.createDate = createDate;
	}

	public String getIntentionLevel() {
		return this.intentionLevel;
	}

	public void setIntentionLevel(String intentionLevel) {
		this.intentionLevel = intentionLevel;
	}

	public Long getCourseTypeId() {
		return this.courseTypeId;
	}

	public void setCourseTypeId(Long courseTypeId) {
		this.courseTypeId = courseTypeId;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getCrmFollows() {
		return this.crmFollows;
	}

	public void setCrmFollows(Set crmFollows) {
		this.crmFollows = crmFollows;
	}

}
