package com.crm.pojo;
// Generated 2017-7-24 17:26:14 by Hibernate Tools 5.2.3.Final

/**
 * CrmRunoff generated by hbm2java
 */
public class CrmRunoff implements java.io.Serializable {

	private Long runOffId;
	private CrmStaff crmStaff;
	private CrmStudent crmStudent;
	private Long createDate;
	private String isRefund;
	private String refundAmount;
	private String remark;

	public CrmRunoff() {
	}

	public CrmRunoff(CrmStudent crmStudent) {
		this.crmStudent = crmStudent;
	}

	public CrmRunoff(CrmStaff crmStaff, CrmStudent crmStudent, Long createDate, String isRefund, String refundAmount,
			String remark) {
		this.crmStaff = crmStaff;
		this.crmStudent = crmStudent;
		this.createDate = createDate;
		this.isRefund = isRefund;
		this.refundAmount = refundAmount;
		this.remark = remark;
	}

	public Long getRunOffId() {
		return this.runOffId;
	}

	public void setRunOffId(Long runOffId) {
		this.runOffId = runOffId;
	}

	public CrmStaff getCrmStaff() {
		return this.crmStaff;
	}

	public void setCrmStaff(CrmStaff crmStaff) {
		this.crmStaff = crmStaff;
	}

	public CrmStudent getCrmStudent() {
		return this.crmStudent;
	}

	public void setCrmStudent(CrmStudent crmStudent) {
		this.crmStudent = crmStudent;
	}

	public Long getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Long createDate) {
		this.createDate = createDate;
	}

	public String getIsRefund() {
		return this.isRefund;
	}

	public void setIsRefund(String isRefund) {
		this.isRefund = isRefund;
	}

	public String getRefundAmount() {
		return this.refundAmount;
	}

	public void setRefundAmount(String refundAmount) {
		this.refundAmount = refundAmount;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
