package com.crm.pojo;
// Generated 2017-7-24 17:26:14 by Hibernate Tools 5.2.3.Final

/**
 * CrmStation generated by hbm2java
 */
public class CrmStation implements java.io.Serializable {

	private Long stationId;
	private CrmStaff crmStaff;
	private CrmStudent crmStudent;
	private String flag;
	private Long createDate;
	private Long beforeClassId;
	private Long afterClassId;

	public CrmStation() {
	}

	public CrmStation(CrmStaff crmStaff, CrmStudent crmStudent, String flag, Long createDate, Long beforeClassId,
			Long afterClassId) {
		this.crmStaff = crmStaff;
		this.crmStudent = crmStudent;
		this.flag = flag;
		this.createDate = createDate;
		this.beforeClassId = beforeClassId;
		this.afterClassId = afterClassId;
	}

	public Long getStationId() {
		return this.stationId;
	}

	public void setStationId(Long stationId) {
		this.stationId = stationId;
	}

	public CrmStaff getCrmStaff() {
		return this.crmStaff;
	}

	public void setCrmStaff(CrmStaff crmStaff) {
		this.crmStaff = crmStaff;
	}

	public CrmStudent getCrmStudent() {
		return this.crmStudent;
	}

	public void setCrmStudent(CrmStudent crmStudent) {
		this.crmStudent = crmStudent;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Long getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Long createDate) {
		this.createDate = createDate;
	}

	public Long getBeforeClassId() {
		return this.beforeClassId;
	}

	public void setBeforeClassId(Long beforeClassId) {
		this.beforeClassId = beforeClassId;
	}

	public Long getAfterClassId() {
		return this.afterClassId;
	}

	public void setAfterClassId(Long afterClassId) {
		this.afterClassId = afterClassId;
	}

}
