package com.crm.pojo;
// Generated 2017-7-24 17:26:14 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CrmStudent generated by hbm2java
 */
public class CrmStudent implements java.io.Serializable {

	private Long studentId;
	private CrmClass crmClass;
	private String stuName;
	private String telephone;
	private String identity;
	private String qq;
	private String gender;
	private Integer mustTuition;
	private Integer actualTuition;
	private String email;
	private String school;
	private String education;
	private String professional;
	private String identityAddress;
	private String address;
	private String remark;
	private String homeTelephone;
	private String homeContact;
	private String status;
	private Set crmRunoffs = new HashSet(0);
	private Set crmGraduates = new HashSet(0);
	private Set crmStations = new HashSet(0);

	public CrmStudent() {
	}

	public CrmStudent(CrmClass crmClass, String stuName, String telephone, String identity, String qq, String gender,
			Integer mustTuition, Integer actualTuition, String email, String school, String education,
			String professional, String identityAddress, String address, String remark, String homeTelephone,
			String homeContact, String status, Set crmRunoffs, Set crmGraduates, Set crmStations) {
		this.crmClass = crmClass;
		this.stuName = stuName;
		this.telephone = telephone;
		this.identity = identity;
		this.qq = qq;
		this.gender = gender;
		this.mustTuition = mustTuition;
		this.actualTuition = actualTuition;
		this.email = email;
		this.school = school;
		this.education = education;
		this.professional = professional;
		this.identityAddress = identityAddress;
		this.address = address;
		this.remark = remark;
		this.homeTelephone = homeTelephone;
		this.homeContact = homeContact;
		this.status = status;
		this.crmRunoffs = crmRunoffs;
		this.crmGraduates = crmGraduates;
		this.crmStations = crmStations;
	}

	public Long getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Long studentId) {
		this.studentId = studentId;
	}

	public CrmClass getCrmClass() {
		return this.crmClass;
	}

	public void setCrmClass(CrmClass crmClass) {
		this.crmClass = crmClass;
	}

	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getIdentity() {
		return this.identity;
	}

	public void setIdentity(String identity) {
		this.identity = identity;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Integer getMustTuition() {
		return this.mustTuition;
	}

	public void setMustTuition(Integer mustTuition) {
		this.mustTuition = mustTuition;
	}

	public Integer getActualTuition() {
		return this.actualTuition;
	}

	public void setActualTuition(Integer actualTuition) {
		this.actualTuition = actualTuition;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getProfessional() {
		return this.professional;
	}

	public void setProfessional(String professional) {
		this.professional = professional;
	}

	public String getIdentityAddress() {
		return this.identityAddress;
	}

	public void setIdentityAddress(String identityAddress) {
		this.identityAddress = identityAddress;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getHomeTelephone() {
		return this.homeTelephone;
	}

	public void setHomeTelephone(String homeTelephone) {
		this.homeTelephone = homeTelephone;
	}

	public String getHomeContact() {
		return this.homeContact;
	}

	public void setHomeContact(String homeContact) {
		this.homeContact = homeContact;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getCrmRunoffs() {
		return this.crmRunoffs;
	}

	public void setCrmRunoffs(Set crmRunoffs) {
		this.crmRunoffs = crmRunoffs;
	}

	public Set getCrmGraduates() {
		return this.crmGraduates;
	}

	public void setCrmGraduates(Set crmGraduates) {
		this.crmGraduates = crmGraduates;
	}

	public Set getCrmStations() {
		return this.crmStations;
	}

	public void setCrmStations(Set crmStations) {
		this.crmStations = crmStations;
	}

}
